(********************************************************)
(*                                                      *)
(*                Malte System/External                 *)
(*                     1993/03/04                       *)
(*                                                      *)
(*      Copyright (C) par les Chevaliers de Malte       *)
(*                                                      *)
(********************************************************)

{ EXTERNAL.INC }

{$DEFINE EXTERNAL}
{$DEFINE __EXTERNAL__}

{End File.}