(********************************************************)
(*                                                      *)
(*               Malte Catalog (Version 286)            *)
(*                      1993/02/04                      *)
(*                                                      *)
(*      Copyright (C) par les Chevaliers de Malte       *)
(*                                                      *)
(********************************************************)

Program MCat286;

{$I CPU80286.INC }
{$I MCATMAIN.INC }

BEGIN
 MCatMain;
END.