(********************************************************)
(*                                                      *)
(*         Malte Catalog/Central Message Library        *)
(*                     1993/05/11                       *)
(*                                                      *)
(*     Copyright (C) par les Chevaliers de Malte        *)
(*                                                      *)
(********************************************************)

{CML/MalteFile}

Const

       { Anglais }

      EnglishTitleViewFiles =
       'View files';

      MsgEnglishNone =
       'None';

      errmsgEnglishDiskInfoEmpty =
       'Sorry! Disk information file is empty!';

      errmsgEnglishIndexEmpty =
       'Sorry! Index file is empty!';

      errmsgEnglishRecordNotFound =
       'Sorry! Record not found!';

      warmsgEnglishContinueSearch =
       'Continue search ?';

       { Francais }

      FrenchTitleViewFiles =
       'Regarde les fichiers';

      MsgFrenchNone =
       'Aucune';

      errmsgFrenchDiskInfoEmpty =
       'D‚sol‚! Le fichier information disque est vide!';

      errmsgFrenchIndexEmpty  =
       'D‚sol‚! Le fichier index est vide!';

      errmsgFrenchRecordNotFound =
       'D‚sol‚! Enregistrement introuvable!';

      warmsgFrenchContinueSearch =
       'Je continue … cherche ?';

{CML/EndOfFile}