(********************************************************)
(*                                                      *)
(*                     Malte Catalog                    *)
(*                      1993/01/23                      *)
(*                                                      *)
(*      Copyright (C) par les Chevaliers de Malte       *)
(*                                                      *)
(********************************************************)

Program MCat;

{$I MCATMAIN.INC }

BEGIN
 MCatMain;
END.
