(********************************************************)
(*                                                      *)
(*                Malte System/Overlay                  *)
(*                     1993/03/04                       *)
(*                                                      *)
(*      Copyright (C) par les Chevaliers de Malte       *)
(*                                                      *)
(********************************************************)

{ OVERLAY.INC }

{$O+}

{$DEFINE OVERLAY}
{$DEFINE __OVERLAY__}

{End File.}